add novelty data to sqlite db
f-hafner/mag_sample pull request #47
Opened 2024-01-20 15:21 UTC by chrished

Add novelty and reuse data based on textual metrics from:

Arts S, Melluso N, Veugelers R (2023). Beyond citations: Text-based metrics for assessing novelty and its impact in scientific publications. https://doi.org/10.48550/arXiv.2309.16437

Paper: https://doi.org/10.48550/arXiv.2309.16437
Data: https://zenodo.org/record/8283353 (DOI: 10.5281/zenodo.8283353)
Code: https://github.com/nicolamelluso/science-novelty

2024-01-31 16:37 UTC, chrished commented
- [ ] adjust loading script to drop existing table
- [ ] add measures from novelty_reuse table to author_output_total and author_output_firstauthor tables
- [ ] adjust author_output table if necessary

2024-01-31 16:54 UTC, chrished commented
- [ ] run and test new author_output table

2024-01-31 20:12 UTC, chrished commented
@f-hafner anything that should be changed/added?

2024-02-01 07:25 UTC, f-hafner requested changes
I made some comments.

2024-02-01 07:25 UTC, f-hafner commented on src/dataprep/main/load_novelty_reuse/dump_db.sh
> +EOF
can you add an index on `PaperId`?

2024-02-01 07:25 UTC, f-hafner commented on src/dataprep/main/load_novelty_reuse/dump_db.sh
> +#!/bin/sh
I noted in the current db that the first row contains again the column names. I think, if the csv files has headers, these must be dropped when using the `.import`  in sqlite. (I don't remember exactly how to do it, but I think we're doing that in other files too)

2024-02-01 07:25 UTC, f-hafner commented on src/dataprep/temp/prep_linked_data.log
> +Time elapsed: 0.30106003681818644 minutes
any idea why it is running faster now?

2024-02-01 17:22 UTC, f-hafner approved these changes

2024-02-01 17:23 UTC, merged

2024-02-01 17:23 UTC, f-hafner commented
thanks!